sudo: false

language: c

compiler:
  - gcc
  - clang

env:
  global:
    secure: "M5SI248QO1XFTVhQXGHUDeUC/mkHj5fo51tDDoUFOwtlV0vMwrk7wb1s4W1PbOZWAkt2gad1Ilfjgv/+l1y2uQSPq08Ih4ubYNdbAXchycDkJnctnNyLCQ/B+4eVJocu9GDeQxfMpOByKfvwCgDhtzeIMV1OfIFtzOdwOySEP5c="

script: autoreconf -if && ./configure && make distcheck

after_success:
  - export DIST_FILE=$(ls teepot-*.tar.gz)
  - export MD5_FILE=$DIST_FILE.md5
  - md5sum $DIST_FILE > $MD5_FILE
  - export SHA256_FILE=$DIST_FILE.sha256
  - shasum -a 256 $DIST_FILE > $SHA256_FILE

deploy:
  provider: releases
  api-key: $GH_OAUTH
  file:
    - $DIST_FILE
    - $MD5_FILE
    - $SHA256_FILE
  skip_cleanup: true
  on:
    condition: "$CC = gcc"
    tags: true
    all_branches: true

